### ISSUE TITLE
Add cjcodes Public Key for Admin User to base-os Ansible Role.

### ISSUE THREAD

**Issue by sheyd** [CrisisTextLine/EnclaveData#16]

**Comment by sheyd** [comment]
@cjcodes Can you attach, link, or paste your public key in this ticket?

**Comment by cjcodes** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEVHqGRZF/js5P2CnICSI6UB2kc6QQ73F+DnOyoggoydHgOle79pup1FcaMDlG8NrjLvbP+KrulTQU0ErqrzlqL/PhiVV+saDl14XTXuT7eVOEMD4mauxUqRRiBo3lmviYVgzPQ7xdn0m3nhmJWUrh4L7+X7ESAgjYWKdJ2VWiI5ZXPx5XlljHTO9b6nmTgsRnw4yRDokyV3W7144mJxTFolZEAIW78Ul88rejYVVCK58NnfQpHvdy6lnn3vXbzLmTSCNG6wIZaqUaHjahTBSSw9vxMnUfxbH2rDn5R7KlYti7p4qO6scdfeyz5jmJtZEvbm6rmdj4YARaEoyVQpGr
